	<div class="col-md-offset-2 col-md-3 col-xs-10">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Contato</h3>
			</div>
			<div class="panel-body">
				<address>
					<strong>Rodokar</strong><br>
					Av 8 - Setor Vila Milena<br>
					Paraiso do Tocantins, TO<br>
					<abbr title="Phone">Telefone: </abbr> (63) 3602-1934
				</address>

				<address>
					<strong>E-mail</strong><br>
					<a href="mailto:#">rodokar@rodokar.com.br</a>
				</address>
			</div>
		</div>
	</div>
	<div class="col-md-7 col-xs-6">
		<iframe width="560" height="420" frameborder="0" style="border:0"
		src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCJQ8CKVkekNoSSrTHRBsOhKACNT4mPv5o&q=RODOKAR+Tacográfo,Paraiso+do+Tocantins+Brasil" allowfullscreen>
		</iframe>
	</div>

