
	<div class="row">
		<div class="col-md-8">   
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
					<li data-target="#carousel-example-generic" data-slide-to="2"></li>
					<li data-target="#carousel-example-generic" data-slide-to="3"></li>
					<li data-target="#carousel-example-generic" data-slide-to="4"></li>
					<li data-target="#carousel-example-generic" data-slide-to="5"></li>
					<li data-target="#carousel-example-generic" data-slide-to="6"></li>
					<li data-target="#carousel-example-generic" data-slide-to="7"></li>

				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="<?=IMG?>frente.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>
					<div class="item">
						<img src="<?=IMG?>rolo.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>
					<div class="item">
						<img src="<?=IMG?>frente2.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>
					<div class="item">
						<img src="<?=IMG?>rolo2.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>
					<div class="item">
						<img src="<?=IMG?>bancada.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>
					<div class="item">
						<img src="<?=IMG?>bancada2.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>
					<div class="item">
						<img src="<?=IMG?>patio.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>
					<div class="item">
						<img src="<?=IMG?>equipamentos.jpg" alt="..."/>
						<div class="carousel-caption">

						</div>
					</div>


					<!-- ... -->
				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
            <!-- /.col-md-8 -->
            <div class="col-md-4">
                <h1>Rodokar Peças e Serviços Tacográfos</h1>
                <p>Empresa voltada para Aferição, Selagem e Ensaio de Tacografós</p>
                <span class="label label-default">Autorizadas</span>
                <img src="<?php echo IMG;?>fipp-img.png" alt="">
            </div>
            <!-- /.col-md-4 -->
        </div>
        <!-- /.row -->

        <hr>
        <div class="row">
            <div class="col-md-6">
                <h2>Serviços</h2>
                <p>Rodokar está aqui para lhe oferecer os melhores serviços de Selagem, Aferição, Ensaio e Conserto de Tacógrafos.</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
            <!-- /.col-md-4 -->
            <div class="col-md-6">
                <h2>Peças</h2>
                <p>Nosso estoque tem todo o suporte necessário para reparo de seu equipamento.</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
            
        </div>
        <!-- /.row -->
	
<!--key=AIzaSyCfyXJI3BEHME0CKEzjLr-p5qiZNCZdI3M -->
       
        
                
