<div class="body col-md-12 col-xs-12 col-lg-12">
		   <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="5"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="6"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="7"></li>
			    
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
			    <div class="item active">
			      <img src="<?=IMG?>frente.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			    <div class="item">
			      <img src="<?=IMG?>rolo.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			    <div class="item">
			      <img src="<?=IMG?>frente2.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			     <div class="item">
			      <img src="<?=IMG?>rolo2.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			     <div class="item">
			      <img src="<?=IMG?>bancada.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			     <div class="item">
			      <img src="<?=IMG?>bancada2.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			     <div class="item">
			      <img src="<?=IMG?>patio.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			     <div class="item">
			      <img src="<?=IMG?>equipamentos.jpg" alt="..."/>
			      <div class="carousel-caption">
			        
			      </div>
			    </div>
			     

			    <!-- ... -->
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
		</div>
		<div class="informacoesindex">	
			<div class="row">
				<div class="col-md-5 col-md-offset-1">
					<div class="panel panel-info">
						<div class="panel-heading">
						<h3 class="panel-title">Serviços</h3>
						</div>
						<div class="panel-body">
							<p class="text-muted">Rodokar está aqui para lhe oferecer os melhores serviços de Selagem, Aferição, Ensaio e Conserto de Tacógrafos.</p>
							<a href="#">Saiba Mais</a>
						</div>
					</div>
				</div>
				<div class="col-md-5">
					<div class="panel panel-info">
						<div class="panel-heading">
						<h3 class="panel-title">Peças</h3>
						</div>
						<div class="panel-body">
							<p class="text-muted">Nosso estoque tem todo o suporte necessário para reparo de seu equipamento. </p>
							<a href="#">Saiba Mais</a>
						</div>
					</div>
				</div>
			</div>
		</div>	
</div>
<!--key=AIzaSyCfyXJI3BEHME0CKEzjLr-p5qiZNCZdI3M -->
       
        
                
