-- MySQL Script generated by MySQL Workbench
-- 09/17/15 14:46:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema espanglish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema espanglish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `espanglish` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `espanglish` ;

-- -----------------------------------------------------
-- Table `espanglish`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espanglish`.`paises` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espanglish`.`votos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espanglish`.`votos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `cpf` VARCHAR(255) NOT NULL COMMENT '',
  `id_pais` INT(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `votos_paises_idx` (`id_pais` ASC)  COMMENT '',
  CONSTRAINT `votos_paises`
    FOREIGN KEY (`id_pais`)
    REFERENCES `espanglish`.`paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
