</div>
		<footer>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-md-offset-5 col-xs-offset-3">
                    <p>Copyright &copy; RODOKAR <?php echo date("Y"); ?></p>
                </div>
            </div>
        </footer>
    
	<script src="<?php echo BOWER;?>jquery/dist/jquery.min.js" type="text/javascript"></script>
	<script src="<?php echo BOWER;?>bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
</body>
</html>