</div>
		<footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; RODOKAR <?php echo date("Y"); ?></p>
                </div>
            </div>
        </footer>
    
	<script src="<?php echo BOWER;?>jquery/dist/jquery.js" type="text/javascript"></script>
	<script src="<?php echo BOWER;?>bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
	<?php echo $add_js;?>
</body>
</html>