		</section>
		<footer>
			<div class="container">
				<div class="row">
					<div class="espaco col-md-4 col-md-offset-4 text-center">
						<p>RODOKAR <?php echo date("Y"); ?> &copy; - Todos os direitos reservados</p>
					</div>
				</div>
			</div>
		</footer>
	<script src="<?php echo BOWER;?>jquery/dist/jquery.min.js" type="text/javascript"></script>
	<script src="<?php echo BOWER;?>bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
</body>
</html>